# See: https://github.com/actions/starter-workflows/blob/main/ci/makefile.yml
# See: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-ruby

name: Check syntax

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Raptor RDF utilities
        run: sudo apt-get update -yq && sudo apt-get install -yq raptor2-utils
      - name: Install Ruby and RDF.rb
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run the checks
        run: make check
